### ISSUE TITLE
Requesting PostgreSQL database structure

### ISSUE THREAD

**Issue by mnewlife** [gidonkatten/igbob-server#2]
Thank you for sharing this code. May you please share a database dump or your database structure so that I can fully run the demo. The file `db.js` only shows how to connect to the database

**Comment by gidonkatten** [comment]
Unfortunately I have deleted my database but you should be able to work out the database from the SQL queries in https://github.com/gidonkatten/igbob-server/tree/main/routes. If you have any questions on that or need help working out the structure then I can assist you in doing so.

**Comment by mnewlife** [comment]
Thank you for your response. I'll try to work out the database and I'll get back to you if I run into any challenges.

**Comment by rahulserver** [comment]
@gidonkatten I am trying to run the server repo and need a bit of assistance with recovering the db structure. @createinnovative were you able to run it? can you send the db structure? (CREATE statements only)

**Comment by rahulserver** [comment]
also @gidonkatten is there any live url for this project?(now that there is no app on heroku)

**Comment by gidonkatten** [comment]
@rahulserver there is no live url anymore and I imagine it will be difficult to get something running which actually works considering it has been such a long time. If it is helpful, I did create a doc of the database structure https://docs.google.com/spreadsheets/d/1o10evfi3AlVx8i_Dluu93eJAiAUSBED2WQ9z0JLmmmI/edit?usp=sharing for the previous person

**Comment by rahulserver** [comment]
Thanks for this. there were minimal changes I had to make. But overall this the working db. 
However I had to make 2 changes: the stablecoin ID does not seem to work, so I had to change that.

**Comment by Sergio997xp** [comment]
So on running this based on the db structure you provided, I am getting this error:

```
Uncaught (in promise) URLTokenBaseHTTPError: Network request error. Received status 400 (): TransactionPool.Remember: transaction FFPNJQETNUAG6O3BUVE7K3QAV5U4JKESNBA54ZYHFMQ2I6ECIXEA: logic eval error: assert failed pc=1190. Details: pc=1190, opcodes=<=; &&; assert
    at URLTokenBaseHTTPClient.checkHttpError (urlTokenBaseHTTPClient.ts:134:1)
    at async URLTokenBaseHTTPClient.formatFetchResponse (urlTokenBaseHTTPClient.ts:144:1)
    at async HTTPClient.post (client.ts:269:1)
    at async SendRawTransaction.do (sendRawTransaction.ts:53:1)
    at async buyBond (Buy.tsx:88:1)
    at async handleBuy (BuyContainer.tsx:82:1)
checkHttpError @ urlTokenBaseHTTPClient.ts:134
await in checkHttpError (async)
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
index.js:1 
```

So any clues on how to debug this pc=1190 error?

**Comment by gidonkatten** [comment]
@Sergio997xp The smart contract check on the stablecoin payment is failing https://github.com/gidonkatten/igbob/blob/main/src/algorand/bond/Buy.tsx#L57-L66. If you mentioned you changed the stablecoin id, then you would need to make the same changes in in the smart contract and transaction you submit?

**Comment by Sergio997xp** [comment]
@gidonkatten  Could you please provide a link to a faucet that will enable us to get some balance?
